const MyProducts = [
  {
    id: 101,
    Name: "socks",
    Rating: 4,
    Description:
      "1/5/10pairs Men Women Socks Comfortable Breathable Ankle Socks Spring Summer",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "socks",
    Image: "/images/socks.png",
    subImages:[
      {img:"./images/socks11.png"},
      {img:"./images/socks12.png"},
      {img:"./images/socks13.png"}
    ],
    orignalPrice:200,
    Discount:50,
    DiscountAllowed:100,
    tagLine:"Smooth and Comfortable Socks"



  },
  {
    id: 102,
    Name: "Wallet",
    Rating: 4,
    Description: "1pc Men'S Slim Casual Faux Leather Wallet - Short Bifold with Multiple Card Slots, Large Capacity, Travel-Friendly, Ideal Birthday and Festival Gift",
    Price: 200,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet.png",
  },
  {
    id: 103,
    Name: "Wallet",
    Rating: 5,
    Description:
      "1pc Elegant PU Leather Large Capacity Ultra-thin Wallet With Multi-card Slot, Ideal Gift For Men",
    Price: 150,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet2.png",
  },
  {
    id: 104,
    Name: "Wallet",
    Rating: 4,
    Description:
      "Stylish Men's Faux Leather Wallet - Large Capacity, Black Travel Card Holder - Perfect Birthday or Holiday Gift",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet3.png",
  },
  {
    id: 105,
    Name: "Wallet",
    Rating: 4,
    Description:
      "1pc Men's Fashion Faux Leather Credit Card Wallet, Slim and Soft Design, Multi-Card Holder, Business Style, Non-Washable, Solid Color, Black",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet4.png",
  },
  {
    id: 106,
    Name: "Wallet",
    Rating: 4,
    Description:
      "Men's Long Wallet & Card Holder With Money Clip, Id Photo Frame And Multiple Card Slots, Ultrathin Soft PU Leather Wallet Card Organizer. Hand-held Clutch, Card Holder, Multi-functional Bag, Card Holder, Ticket Folder, Money Coin Pocket.",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet5.png",
  },
  {
    id: 107,
    Name: "Wallet",
    Rating: 4,
    Description:
      "Sleek Men's Mini Wallet - Ultra-Thin, Lightweight with Card Slots & ID Holder, Faux Leather",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet6.png",
  },
  {
    id: 108,
    Name: "Wallet",
    Rating: 4,
    Description:
      "Men's Classic Vintage Style Simple Short Wallet with Coin Pouch - PU Material, Solid Color, Non-Braided, Polyester Lined",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet7.png",
  },
  {
    id: 109,
    Name: "Wallet",
    Rating: 4,
    Description:"Sleek Men's Faux Leather Wallet - Slim, Portable Design with Solid Color Options",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet8.png",
  },
  {
    id: 110,
    Name: "Wallet",
    Rating: 4,
    Description:
      "1pc Men's Trendy And Versatile Iron-edged Wallet, With Multiple Card Slots PU Leather Wallet",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet9.png",
  },
  {
    id: 111,
    Name: "Wallet",
    Rating: 4,
    Description: "Men's Card Holder, 8 Card Slots Credit Card Bag Holder",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Wallet",
    Image: "/images/wallet10.png",
  },
  //WALLLETS FINISHED
  {
    id: 112,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's 3D Digital Print Color Block T-Shirt, Breathable Mesh Fabric, Casual Round Neck Short Sleeve Tee, Summer Fashion Streetwear, Polyester Knit Top for Sports and Leisure",
    Price: 100,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt1.png",
  },
  {
    id: 113,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Coconut Tree Print Men's Color Block Striped Short Sleeve Zipper Lapel Shirt, Men's Summer Clothing, Leisure And Street",
    Price: 800,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt2.png",
  },
  {
    id: 114,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's 3pcs Casual Crew Neck Sweatshirt Set - Solid Color, Polyester Blend, Machine Washable - Perfect for All Seasons, for Autumn,",
    Price: 4612,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt3.png",
  },
  {
    id: 115,
    Name: "Shirt",
    Rating: 4,
    Description:
      "1pc Men'S Fashion Slim Fit Long Sleeve Dress Shirt - Solid Color, Button-Up, Polyester, Non-Stretch, Notched Collar, Suitable for All Seasons",
    Price: 2127,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt4.png",
  },
  {
    id: 116,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Pearson OBM Men's Casual Long Sleeve Golf Shirt with Button Detail - 100% Polyester Knit Fabric, Regular Fit Solid Color Shirt with Polo Collar and Slight Stretch for Fall/Winter",
    Price: 2202,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt4.png",
  },
  {
    id: 117,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's Fashion Striped Print Shirts, Casual Breathable Lapel Button Long Sleeve Shirt For Spring/Fall",
    Price: 2301,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt5.png",
  },
  {
    id: 118,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's Casual Breathable Long Sleeve Button Shirt With Gradient Print For Spring/Autumn",
    Price: 2401,
    Tag: "Best Seller",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt6.png",
  },
  {
    id: 119,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men'S Fashion Casual Crew Neck T-Shirt, 100% Polyester, Regular Fit, with Geometric Stripe Pattern, with Slight Stretch",
    Price: 1216,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt7.png",
  },
  {
    id: 120,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's Lion Graphic Print T-shirt, Short Sleeve Crew Neck Tee, Men's Clothing For Summer Outdoor",
    Price: 1245,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt8.png",
  },
  {
    id: 121,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's Casual Striped Crew Neck T-Shirt - 100% Polyester Knit Fabric with Slight Stretch, Breathable & Soft, Summer Digital Print Tee with Regular Fit",
    Price: 1681,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt9.png",
  },
  {
    id: 122,
    Name: "Shirt",
    Rating: 4,
    Description:
      "Men's Summer Casual Short Sleeve Lapel Golf Shirt With Chest Pocket, Suitable For Daily Wear",
    Price: 1543,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Shirt",
    Image: "/images/shirt10.png",
    //shirts Finsihsed
  },
  {
    id: 123,
    Name: "Jeans",
    Rating: 3,
    Description:
      "Men's Solid Denim Trousers With Pockets, Causal Cotton Blend Slim-fit Jeans For Outdoor Activities",
    Price: 4579,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans1.png",
  },
  {
    id: 124,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Semi-formal Jeans, Chic Classic Design Straight Leg Jeans For Businesss",
    Price: 3876,
    Tag: "Top Rated",
    Category: "mens",

    subCategory: "Jeans",
    Image: "/images/jeans2.png",
  },
  {
    id: 125,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Solid Denim Jeans, Light Business Style Slightly Stretch Straight Leg Pants For Outdoor Casual Daily",
    Price: 4475,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans3.png",
  },
  {
    id: 126,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Casual Business Jeans, Stretchy Regular Fit Straight Leg Pants, Suitable For All Seasons",
    Price: 4534,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans4.png",
  },
  {
    id: 127,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Classic Design Jeans, Semi-formal Stretch Jeans For Business",
    Price: 4377,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans5.png",
  },
  {
    id: 128,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Semi-formal Jeans, Chic Classic Design Stretch Jeans For Business",
    Price: 4197,
    Tag: "Top Rated ",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans6.png",
  },
  {
    id: 129,

    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Semi-formal Jeans, Chic Classic Design Straight Leg Jeans For Business",
    Price: 3969,
    Tag: "Top Rated",

    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans7.png",
  },
  {
    id: 130,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Classic Straight-Leg Jeans - Versatile for Business & Casual Wear, Cotton Blend, Machine Washable",
    Price: 4194,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans8.png",
  },
  {
    id: 131,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men'S Skinny Fit Jeans - Cotton Blend with Elastane, Basic Solid Color, Slight Stretch, Washed Detail, All-Season Wear",
    Price: 4811,
    Tag: "Top Rated",

    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans9.png",
  },
  {
    id: 132,
    Name: "Jeans",
    Rating: 4,
    Description:
      "Men's Slim Fit Stretch Jeans - Casual, Breathable Cotton Blend Denim Pants with Machine Washable Feature",
    Price: 4900,
    Tag: "Top Rated",
    Category: "mens",
    subCategory: "Jeans",
    Image: "/images/jeans10.png",
  },
  //Jeans Finished
];

export default MyProducts;